# the Technology class.
class: "templates_cds_ff_mpt.tech.TechInfoCDSFFMPT"

# layout related parameters
layout:
  # default EM spec calculation settings
  em:
    # DC current temperature
    dc_temp: !!int 70
    # RMS current allowable temperature increase
    rms_dt: !!int 10

# transistor technology parameters
mos:
  # the transistor width minimum resolution.
  width_resolution: !!float 1
  # the transistor length minimum resolution.
  length_resolution: !!float 1e-9

# routing grid parameters
routing_grid:
  1: [y, 60,  60,  [[60, 61], [80, 81], [120, .inf]]]
  2: [x, 60,  60,  [[60, 61], [80, 81], [120, .inf]]]
  3: [y, 60,  60,  [[60, 61], [80, 81], [120, .inf]]]
  4: [x, 60,  60,  [[60, 61], [80, 81], [120, .inf]]]
  5: [y, 80,  100, [[80, 81], [120, .inf]]]
  6: [x, 80,  100, [[80, 81], [120, .inf]]]
  7: [y, 80,  100, [[80, 81], [120, .inf]]]
  8: [x, 160, 200, [[160, .inf]]]
