# the Technology class.
class: "templates_cds_ff_mpt.tech.TechInfoCDSFFMPT"

# layout related parameters
layout:
  # default EM spec calculation settings
  em:
    # DC current temperature
    dc_temp: !!int 70
    # RMS current allowable temperature increase
    rms_dt: !!int 10
  # AnalogBase parameters
  analog_base:
    # minimum number of fingers separation.
    min_fg_sep: 2
    mconn_diff_mode: False
    floating_dummy: False

# transistor technology parameters
mos:
  # the transistor width minimum resolution.
  width_resolution: !!float 1
  # the transistor length minimum resolution.
  length_resolution: !!float 1e-9
